blank_issues_enabled: true
contact_links:
  - name: Problem with me3
    url: https://github.com/Lexcellent/me3/discussions/new?category=bug-reports
    about: Having issues using me3? Get help or report them here.
